"""LLM client interface and mock implementation.

The real client (Phase 3) MUST match this interface exactly so the API layer
doesn't change. The mock streams a fixed string token-by-token.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator
from typing import Literal, Protocol

from pydantic import BaseModel

from devdocs_rag.config import get_settings

logger = logging.getLogger(__name__)


Role = Literal["system", "user", "assistant"]


class LLMMessage(BaseModel):
    role: Role
    content: str


class LLMClient(Protocol):
    """Every LLM client (mock or real) must satisfy this protocol.

    `stream` is an async-generator function — declared with a regular `def`
    returning `AsyncIterator[str]` (not `async def`), because async generators
    return their iterator synchronously and the caller iterates with
    `async for`.
    """

    def stream(self, messages: list[LLMMessage]) -> AsyncIterator[str]:
        """Yield tokens (or token-like fragments) one at a time."""
        ...

    async def complete(self, messages: list[LLMMessage]) -> str:
        """Non-streaming convenience: collect the full string."""
        ...


_MOCK_RESPONSE = (
    "[mock] devdocs-rag is in Phase 1 — no real LLM is wired yet. "
    "This response is generated by MockLLMClient so the streaming "
    "plumbing can be exercised end-to-end."
)


class MockLLMClient:
    """Deterministic stand-in for a real LLM client.

    Token streaming = split on spaces and yield with a tiny sleep so SSE
    consumers can observe incremental delivery.
    """

    def __init__(self, response: str = _MOCK_RESPONSE, token_delay_s: float = 0.01) -> None:
        self._response = response
        self._token_delay_s = token_delay_s

    async def stream(self, messages: list[LLMMessage]) -> AsyncIterator[str]:
        logger.debug("mock stream", extra={"n_messages": len(messages)})
        for i, token in enumerate(self._response.split(" ")):
            if i > 0:
                yield " "
            yield token
            if self._token_delay_s:
                await asyncio.sleep(self._token_delay_s)

    async def complete(self, messages: list[LLMMessage]) -> str:
        parts: list[str] = []
        async for tok in self.stream(messages):
            parts.append(tok)
        return "".join(parts)


def get_llm_client() -> LLMClient:
    """Return the active LLM client.

    `USE_MOCK_LLM=true` (the default, and the test/CI setting) returns the
    mock; `false` requires `ARK_API_KEY` and returns the real Ark client
    (Phase 6). Misconfiguration raises a typed GenerationError rather than
    silently falling back to the mock.
    """
    settings = get_settings()
    if settings.use_mock_llm:
        return MockLLMClient()

    # Local import: ark_client imports LLMMessage from this module.
    from devdocs_rag.generation.ark_client import ArkLLMClient
    from devdocs_rag.generation.errors import GenerationError

    if not settings.ark_api_key:
        raise GenerationError(
            "USE_MOCK_LLM=false but ARK_API_KEY is not set — refusing to fall back to mock"
        )
    return ArkLLMClient(
        api_key=settings.ark_api_key,
        model=settings.ark_model,
        base_url=settings.ark_base_url,
        temperature=settings.llm_temperature,
        max_tokens=settings.llm_max_tokens,
    )
